# Default values for Go projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: docker.io/jenkins-x/dex
  tag: 2.10.44
  pullPolicy: IfNotPresent

service:
  name: dex
  type: ClusterIP
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"

ports:
  - name: http
    internalPort: 8080
    externalPort: 80
    protocol: TCP
  - name: grpc
    internalPort: 5000
    externalPort: 5000
    protocol: TCP

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 80m
    memory: 128Mi

probePath: /healthz
livenessProbe:
  port: 8080
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  port: 8080
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10

nodeSelector: {}

certs:
  image: gcr.io/google_containers/kubernetes-dashboard-init-amd64
  imageTag: "v1.0.0"
  imagePullPolicy: "IfNotPresent"
  grpc:
    create: true
    activeDeadlineSeconds: 300
    altNames:
      - dex
    altIPs: {}
    ca:
      secretName: dex-grpc-ca
    server:
      secretName: dex-grpc-server-cert

env: []

rbac:
  # Specifies whether RBAC resources should be created
  create: true

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

domain:
connectors:
  github: 
    config:
      type: github
      name: GitHub
      clientID:
      clientSecret:
      orgs:
