{{- if .Values.certs.grpc.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "fullname" . }}-openssl-config
  annotations:
    "helm.sh/hook":pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": hook-succeeded
data:
  openssl.conf: |
{{ .Files.Get "config/openssl.conf" | indent 4 }}
{{- end }}
